"""initial

Revision ID: cf05efdffcd3
Revises: 
Create Date: 2026-10-01 16:31:50.942261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf05efdffcd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_cache',
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_pt', sa.String(length=100), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('is_legendary', sa.Boolean(), nullable=True),
    sa.Column('is_mythical', sa.Boolean(), nullable=True),
    sa.Column('base_happiness', sa.Integer(), nullable=True),
    sa.Column('capture_rate', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('trainer_code', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'friends', 'private'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    op.create_table('forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.String(length=50), nullable=False),
    sa.Column('type1', sa.String(length=20), nullable=True),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('sprite_url', sa.String(length=255), nullable=True),
    sa.Column('is_shiny_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', 'form_name', name='uq_species_form')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forms_species_id'), ['species_id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('evolution_chains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_form_id', sa.Integer(), nullable=False),
    sa.Column('to_form_id', sa.Integer(), nullable=False),
    sa.Column('candy_cost', sa.Integer(), nullable=True),
    sa.Column('candy_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['from_form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['to_form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wisher_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'contacted', 'completed', 'cancelled'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wisher_id', 'owner_id', 'form_id', name='uq_active_match')
    )
    with op.batch_alter_table('trade_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_matches_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_matches_wisher_id'), ['wisher_id'], unique=False)

    op.create_table('user_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_trade', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='chk_quantity_non_negative'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'form_id', name='uq_user_form')
    )
    with op.batch_alter_table('user_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_collections_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_collections_user_id'), ['user_id'], unique=False)

    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'form_id', name='uq_wish_user_form')
    )
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlists_user_id'), ['user_id'], unique=False)

    op.create_table('whatsapp_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('clicker_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clicker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['trade_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_clicks_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_clicks_match_id'))

    op.drop_table('whatsapp_clicks')
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlists_user_id'))

    op.drop_table('wishlists')
    with op.batch_alter_table('user_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_collections_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_collections_form_id'))

    op.drop_table('user_collections')
    with op.batch_alter_table('trade_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_matches_wisher_id'))
        batch_op.drop_index(batch_op.f('ix_trade_matches_owner_id'))

    op.drop_table('trade_matches')
    op.drop_table('evolution_chains')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_species_id'))

    op.drop_table('forms')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('species')
    op.drop_table('pokemon_cache')
    # ### end Alembic commands ###
